### PR TITLE
feat: luarocks support

### PR DESCRIPTION
**Pull request by mrcjkb**
[as requested](https://github.com/nvimtools/none-ls.nvim/pull/103#issuecomment-2032636570) :smile:

### CODE REVIEW

**Comment by mochaaP** [comment]
ty!

**Comment by mochaaP** [comment]
🤔 needs further investigation: https://github.com/nvimtools/none-ls-extras.nvim/actions/runs/8528941209/job/23363638627

**Comment by mochaaP** [comment]
seems -scm tags are only available on the dev package index.

**Comment by mochaaP** [comment]
about the semver problem: can we use a version number like `0.0.0-20240403`?

**Comment by mrcjkb** [comment]
> seems -scm tags are only available on the dev package index.

luarocks can install dev packages with the `--dev` flag. rocks.nvim\s `:Rocks install` command will automatically add that flag if the version is `dev` or `scm`. And it will prompt to search the dev manifest if no release version is found.

> about the semver problem: can we use a version number like 0.0.0-20240403?

That would be a valid luarocks `specrev`, but it isn't currently supported by the luarocks-tag-release workflow (it has it hardcoded as `1` for non-PR workflow runs).

When it comes to [setting dependency version bounds in a rockspec](https://github.com/luarocks/luarocks/wiki/Rockspec-format#dependency-information), I don't think you can use the specrev.

**Comment by mrcjkb** [comment]
> 🤔 needs further investigation: https://github.com/nvimtools/none-ls-extras.nvim/actions/runs/8528941209/job/23363638627

I've created https://github.com/nvim-neorocks/luarocks-tag-release/issues/404 and will fix it after work today.

**Pull request merged**
